### ISSUE TITLE
does it support monorepo with `pnpm`? 

### ISSUE THREAD

**Issue by zigang93** [iamchathu/changeset-conventional-commits#33] opened 2024-03-26 02:58 UTC
when I tried to run `npx changeset-conventional-commits`
it does nothing there

**Comment by iamchathu** [comment] 2024-03-26 10:40
Some debugging steps. 
- [ ]  Do you ran on the root folder where you have .changeset folder?
- [ ]  Does the project is initialized with git and does git is accessible from the path?

It does works with PNPM mono repos and I use it almost every day.

**Comment by mblackrittr** [comment] 2024-03-26 13:52
Ah yeah, definitely does, recognizing both - workspaces defined in `package.json` and `pnpm-workspace.yaml`, so it works with all of "them", `npm`, `yarn`, `pnpm` (which also this package uses) and `bun` (my preference).

You might particularly want to check for:
- [ ] Public/private package
  `"private": "true'` to not be set, or set to '"false"' - which we're already working on to be handled correctly - see:
https://github.com/iamchathu/changeset-conventional-commits/issues/25

If there's no advancement, I'll just throw it in next days, so this package will finally already be "a round thing"! 😻

Also the latest addition MR/PR will surely help you to spot the issue:
[feat: add cli helper, logging and flags --dry, --git-fetch and --verbose #29](https://github.com/iamchathu/changeset-conventional-commits/pull/29).

@iamchathu, can you pull/merge this in?

It seems like it'll resolve this "doing nothing" issue for many people with its `--verbose` and `--dry` flags and output, making the cause easy to spot.

I don't think it should require test coverage for everything - incl. main function, if I saw that right - already just now on that articular MR/PR, because this wasn't added by it.

**Comment by iamchathu** [comment] 2024-03-26 14:34
@mblackrittr Sorry for the delay on reviewing that PR. I have put some comments and let's get that one merged soon.

**Comment by mblackrittr** [comment] 2024-03-26 15:57
> @mblackrittr Sorry for the delay on reviewing that PR.

All good, I was just worried that it stays unnoticed being ready for final input and review - esp. in hindsight of it solving pressing issues. haha

> I have put some comments and let's get that one merged soon.

Ah yeah, super, checked them already and we'll sort these in no time, probably already by tomorrow - just being on a 30h bus trip right now, which is quite nibbling on ones constitution, but might already chime in next hours.

**Closed** 2024-06-04 03:44 UTC
